### ISSUE TITLE
Composer install, /lib empty on deploy to AWS/EB

### ISSUE THREAD

**Issue by ricardo-nolan** [xfra35/f3-access#3]
Trying to use this on AWS - Elastic Beanstalk, on deployment, none of the folders in f3-access exist on the server. I think it may be due to the inclusion of the .git folder in composer which may be breaking EB deployment.

Looks fine on local machine:
/vendor/xfra35/f3-access/lib/access.php
-vendor
--xfra35
---f3-access
----.git
----lib
-----access.php
----tests

but on checking server after deployment, /lib does not exist, nor any other file in /f3-access.
/vendor/xfra35/f3-access is there, but empty.

**Comment by xfra35** [comment]
Hi @rnolan,
Just came back from holiday. Could you fix it? How is your code deployed to AWS?
