### ISSUE TITLE
Error with the newest version of F3

### ISSUE THREAD

**Issue by SaphiLC** [xfra35/f3-access#5]
```
Internal Server Error
session_start(): Failed to decode session object. Session has been destroyed

[vendor/bcosca/fatfree-core/base.php:2190] Base->error()
[vendor/bcosca/fatfree-core/base.php:274] session_start()
[vendor/bcosca/fatfree-core/base.php:415] Base->ref()
[src/bootstrap.php:20] Base->get()
[www/index.php:3] require_once('src\bootstrap.php')


[src/bootstrap.php:20] Base->get()
	19	$access = \Access::instance();
	20	$id = $app->get('SESSION.account.id');
```

the moment i stop using f3-access everything works, and if i load it at any time or place, i get that error the moment i set or get from SESSION.

Any ideas on whats going on?

**Comment by xfra35** [comment]
This is a framework or PHP issue: line 20 matches your call to `'SESSION.account.id'`.

When you call `SESSION` for the first time, it triggers a `session_start()`, and in your case the session files can't be decoded. There could be various reasons for this to happen. For example, this error would happen if you changed the [PHP serializing format setting](http://php.net/manual/en/session.configuration.php#ini.session.serialize-handler) without clearing the session folder.

Try to clear the session folder ([session_save_path()](http://php.net/manual/en/function.session-save-path.php) will return the exact location).

If it doesn't help, just open a thread on the [user forum](https://groups.google.com/forum/#!forum/f3-framework).
